#Make a basic tax conversion calculator with additional conditions like yearly income being doubled and tripled

income: float = float(input("Enter your yearly income in ₹: "))
tax_rate: float = float(input("Enter tax rate % : ")) / 100
taxed: float = float(income * tax_rate)
doubled_income: float = (income * 2)
doubled_tr:float = (doubled_income * tax_rate)
tripled_income: float = (income * 3)
tripled_tr:float = (tripled_income * tax_rate)

print("-" * 52)
print(f"Your yearly income is:     ₹{income:.2f}")
print("." * 52)
print(f"Your yearly tax rate:      {tax_rate:.2%}")
print("=" * 52)
print(f"Your taxed amount is:      ₹{taxed:.2f}")
print("->->" * 13)
print(f"Your yearly income (doubled) is:     ₹{doubled_income:.2f}")
print("." * 52)
print(f"Your yearly (doubled) tax rate:      {tax_rate:.2%}")
print("=" * 52)
print(f"Your taxed amount (doubled) is:      ₹{doubled_tr:.2f}")
print("->->" * 13)
print(f"Your yearly income (tripled) is:     ₹{tripled_income:.2f}")
print("." * 52)
print(f"Your yearly (tripled) tax rate:      {tax_rate:.2%}")
print("=" * 52)
print(f"Your taxed amount (tripled) is:      ₹{tripled_tr:.2f}")
print("->->" * 13)
